In [5]:
# load reviews

import pandas as pd

animes = pd.read_parquet(r"C:\Users\insiy\Documents\Projects_Extracurricular\Anime_Recommedation_System\data\animes.parquet")

In [6]:
C = animes['score'].mean()        # global mean score
m = animes['members'].quantile(0.75)  # minimum members threshold (75th percentile)

def bayesian_rating(row):
    v = row['members']
    R = row['score']
    return (v / (v + m)) * R + (m / (v + m)) * C

animes['weighted_score'] = animes.apply(bayesian_rating, axis=1)

# Top recommendations
top_animes = animes.sort_values('weighted_score', ascending=False).head(10)
top_animes[['title', 'score', 'members', 'weighted_score']]

                                  title  score  members  weighted_score
3      Fullmetal Alchemist: Brotherhood   9.23  1615084        9.205713
773                         Steins;Gate   9.11  1331710        9.081828
772              Hunter x Hunter (2011)   9.11  1052761        9.074460
771                      Kimi no Na wa.   9.09  1139878        9.057383
770  Shingeki no Kyojin Season 3 Part 2   9.07   446370        8.988825
765                      Koe no Katachi   9.01   842277        8.967333
769                            Gintama°   9.05   281594        8.924477
14                 Clannad: After Story   8.97   740101        8.922282
768                            Gintama'   9.04   278110        8.913451
13                              Gintama   8.97   579150        8.909329

In [7]:
# Extract base title (text before any special characters like °, ', :)
import re

# Sort first, then drop duplicates keeping only the highest-ranked entry per base title
top_animes = (
    animes.sort_values('weighted_score', ascending=False)
    .drop_duplicates(subset='base_title', keep='first')
)

most_popular = (
    animes.sort_values('popularity')
    .drop_duplicates(subset='base_title',keep='first')
)

In [8]:
top_animes.head(5)

,uid,title,synopsis,genre,aired,episodes,members,popularity,ranked,score,img_url,link,base_title,weighted_score
3,5114,Fullmetal Alchemist: Brotherhood,"""In order for something to be obtained, someth...","['Action', 'Military', 'Adventure', 'Comedy', ...","Apr 5, 2009 to Jul 4, 2010",64.0,1615084,4,1.0,9.23,https://cdn.myanimelist.net/images/anime/1223/...,https://myanimelist.net/anime/5114/Fullmetal_A...,Fullmetal Alchemist,9.205713
773,9253,Steins;Gate,The self-proclaimed mad scientist Rintarou Oka...,"['Thriller', 'Sci-Fi']","Apr 6, 2011 to Sep 14, 2011",24.0,1331710,7,2.0,9.11,https://cdn.myanimelist.net/images/anime/5/731...,https://myanimelist.net/anime/9253/Steins_Gate,Steins;Gate,9.081828
772,11061,Hunter x Hunter (2011),Hunter x Hunter is set in a world where Hunte...,"['Action', 'Adventure', 'Fantasy', 'Shounen', ...","Oct 2, 2011 to Sep 24, 2014",148.0,1052761,20,3.0,9.11,https://cdn.myanimelist.net/images/anime/11/33...,https://myanimelist.net/anime/11061/Hunter_x_H...,Hunter x Hunter,9.074460
771,32281,Kimi no Na wa.,"Mitsuha Miyamizu, a high school girl, yearns t...","['Romance', 'Supernatural', 'School', 'Drama']","Aug 26, 2016",1.0,1139878,15,4.0,9.09,https://cdn.myanimelist.net/images/anime/5/870...,https://myanimelist.net/anime/32281/Kimi_no_Na_wa,Kimi no Na wa,9.057383
770,38524,Shingeki no Kyojin Season 3 Part 2,Seeking to restore humanity’s diminishing hope...,"['Action', 'Drama', 'Fantasy', 'Military', 'My...","Apr 29, 2019 to Jul 1, 2019",10.0,446370,175,5.0,9.07,https://cdn.myanimelist.net/images/anime/1517/...,https://myanimelist.net/anime/38524/Shingeki_n...,Shingeki no Kyojin Season 3 Part 2,8.988825

In [9]:
most_popular.head(5)

,uid,title,synopsis,genre,aired,episodes,members,popularity,ranked,score,img_url,link,base_title,weighted_score
740,1535,Death Note,"A shinigami, as a god of death, can kill any p...","['Mystery', 'Police', 'Psychological', 'Supern...","Oct 4, 2006 to Jun 27, 2007",37.0,1871043,1,52.0,8.65,https://cdn.myanimelist.net/images/anime/9/945...,https://myanimelist.net/anime/1535/Death_Note,Death Note,8.633255
681,16498,Shingeki no Kyojin,"Centuries ago, mankind was slaughtered to near...","['Action', 'Military', 'Mystery', 'Super Power...","Apr 7, 2013 to Sep 29, 2013",25.0,1754979,2,111.0,8.47,https://cdn.myanimelist.net/images/anime/10/47...,https://myanimelist.net/anime/16498/Shingeki_n...,Shingeki no Kyojin,8.453560
8409,11757,Sword Art Online,"In the year 2022, virtual reality has progress...","['Action', 'Adventure', 'Fantasy', 'Game', 'Ro...","Jul 8, 2012 to Dec 23, 2012",25.0,1657823,3,1771.0,7.49,https://cdn.myanimelist.net/images/anime/11/39...,https://myanimelist.net/anime/11757/Sword_Art_...,Sword Art Online,7.480690
3,5114,Fullmetal Alchemist: Brotherhood,"""In order for something to be obtained, someth...","['Action', 'Military', 'Adventure', 'Comedy', ...","Apr 5, 2009 to Jul 4, 2010",64.0,1615084,4,1.0,9.23,https://cdn.myanimelist.net/images/anime/1223/...,https://myanimelist.net/anime/5114/Fullmetal_A...,Fullmetal Alchemist,9.205713
16,30276,One Punch Man,The seemingly ordinary and unimpressive Saitam...,"['Action', 'Sci-Fi', 'Comedy', 'Parody', 'Supe...","Oct 5, 2015 to Dec 21, 2015",12.0,1475219,5,50.0,8.68,https://cdn.myanimelist.net/images/anime/12/76...,https://myanimelist.net/anime/30276/One_Punch_Man,One Punch Man,8.658526

In [11]:
animes.to_parquet(r"C:\Users\insiy\Documents\Projects_Extracurricular\Anime_Recommedation_System\data\animes.parquet")